name: Build, Test, and Deploy Workflow

on:
  push:
    branches:
       - bugfix/monitor
       - main
       - relese/prod

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          # Add commands to build your code here

      - name: Test
        run: |
          # Add commands to run tests here

      - name: Deploy
        run: |
          # Add commands to deploy your code here
